const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

const FORGOT_USER_REQUEST = "FORGOT_USER_REQUEST";
const FORGOT_USER_SUCCESS = "FORGOT_USER_SUCCESS";
const FORGOT_USER_FAILURE = "FORGOT_USER_FAILURE";


const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";


export const types = {

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  REGISTER_USER_REQUEST,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAILURE,

  FORGOT_USER_REQUEST,
  FORGOT_USER_SUCCESS,
  FORGOT_USER_FAILURE,

  LOGOUT_USER_REQUEST,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_FAILURE,

  
}