const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

const FORGOT_USER_REQUEST = "FORGOT_USER_REQUEST";
const FORGOT_USER_SUCCESS = "FORGOT_USER_SUCCESS";
const FORGOT_USER_FAILURE = "FORGOT_USER_FAILURE";


const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

const VERIFY_USER_REQUEST = "VERIFY_USER_REQUEST";
const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
const VERIFY_USER_FAILURE = "VERIFY_USER_FAILURE";

const RESET_USER_PASSWORD_REQUEST = "RESET_USER_PASSWORD_REQUEST";
const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
const RESET_USER_PASSWORD_FAILURE = "RESET_USER_PASSWORD_FAILURE";

export const types = {

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  REGISTER_USER_REQUEST,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAILURE,

  FORGOT_USER_REQUEST,
  FORGOT_USER_SUCCESS,
  FORGOT_USER_FAILURE,

  LOGOUT_USER_REQUEST,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_FAILURE,

  VERIFY_USER_REQUEST,
  VERIFY_USER_SUCCESS,
  VERIFY_USER_FAILURE,

  RESET_USER_PASSWORD_REQUEST,
  RESET_USER_PASSWORD_SUCCESS,
  RESET_USER_PASSWORD_FAILURE,
}