const GET_ALL_CHATS_REQUEST = "GET_ALL_CHATS_REQUEST";
const GET_ALL_CHATS_SUCCESS = "GET_ALL_CHATS_SUCCESS";
const GET_ALL_CHATS_FAILURE = "GET_ALL_CHATS_FAILURE";

const CREATE_CHATS_REQUEST = "CREATE_CHATS_REQUEST";
const CREATE_CHATS_SUCCESS = "CREATE_CHATS_SUCCESS";
const CREATE_CHATS_FAILURE = "CREATE_CHATS_FAILURE";


export const types = {

  GET_ALL_CHATS_REQUEST,
  GET_ALL_CHATS_SUCCESS,
  GET_ALL_CHATS_FAILURE,

  CREATE_CHATS_REQUEST,
  CREATE_CHATS_SUCCESS,
  CREATE_CHATS_FAILURE,

}