const GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST";
const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
const GET_ALL_PROJECTS_FAILURE = "GET_ALL_PROJECTS_FAILURE";



export const types = {

  GET_ALL_PROJECTS_REQUEST,
  GET_ALL_PROJECTS_SUCCESS,
  GET_ALL_PROJECTS_FAILURE,



}