const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

const GET_MY_PROFILE_REQUEST = "GET_MY_PROFILE_REQUEST";
const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
const GET_MY_PROFILE_FAILURE = "GET_MY_PROFILE_FAILURE";


const UPDATE_MY_PROFILE_REQUEST = "UPDATE_MY_PROFILE_REQUEST";
const UPDATE_MY_PROFILE_SUCCESS = "UPDATE_MY_PROFILE_SUCCESS";
const UPDATE_MY_PROFILE_FAILURE = "UPDATE_MY_PROFILE_FAILURE";

const UPDATE_MY_PROFILE_PIC_REQUEST = "UPDATE_MY_PROFILE_PIC_REQUEST";
const UPDATE_MY_PROFILE_PIC_SUCCESS = "UPDATE_MY_PROFILE_PIC_SUCCESS";
const UPDATE_MY_PROFILE_PIC_FAILURE = "UPDATE_MY_PROFILE_PIC_FAILURE";


export const types = {

  GET_ALL_USERS_REQUEST,
  GET_ALL_USERS_SUCCESS,
  GET_ALL_USERS_FAILURE,

  GET_MY_PROFILE_REQUEST,
  GET_MY_PROFILE_SUCCESS,
  GET_MY_PROFILE_FAILURE,

  UPDATE_MY_PROFILE_REQUEST,
  UPDATE_MY_PROFILE_SUCCESS,
  UPDATE_MY_PROFILE_FAILURE,

  UPDATE_MY_PROFILE_PIC_REQUEST,
  UPDATE_MY_PROFILE_PIC_SUCCESS,
  UPDATE_MY_PROFILE_PIC_FAILURE,

}