const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

const GET_MY_PROFILE_REQUEST = "GET_MY_PROFILE_REQUEST";
const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
const GET_MY_PROFILE_FAILURE = "GET_MY_PROFILE_FAILURE";


export const types = {

  GET_ALL_USERS_REQUEST,
  GET_ALL_USERS_SUCCESS,
  GET_ALL_USERS_FAILURE,

  GET_MY_PROFILE_REQUEST,
  GET_MY_PROFILE_SUCCESS,
  GET_MY_PROFILE_FAILURE

}